
version: '2'
services:
  mysql:
        image: mysql:5.6
        container_name: mysql-server-56
        command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
        volumes:
          - ./mysql:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_USER}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
          - "13306:3306"
  web:
    container_name: php72
    build:
      context: ./
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql